//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class administration
    {
        public int IdDoctor { get; set; }
        public int IdStuff { get; set; }
        public int IdPatient { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual Patiens Patiens { get; set; }
    }
}
