//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentToADoctor
    {
        public int IdAppointmentToADoctor { get; set; }
        public int IdDoctor { get; set; }
        public int IdPatient { get; set; }
        public System.DateTime DateOfMedicalExamination { get; set; }
        public int IdCabinet { get; set; }
        public int IdClinic { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Patiens Patiens { get; set; }
    }
}
